builds:
  - binary: observe
    id: observe
    goos:
      - linux
      - windows
    goarch:
      - amd64
    mod_timestamp: "{{.CommitTimestamp}}"
  - binary: observe
    id: observe-macos-amd64
    goos:
      - darwin
    goarch:
      - amd64
    mod_timestamp: "{{.CommitTimestamp}}"
  - binary: observe
    id: observe-macos-arm64
    goos:
      - darwin
    goarch:
      - arm64
    mod_timestamp: "{{.CommitTimestamp}}"
checksum:
  disable: true
signs:
  - signature: "${artifact}"
    ids:
      - observe-macos-amd64
      - observe-macos-arm64
    cmd: gon
    args:
      - s/notarize.hcl
    artifacts: all
    output: true

