builds:
  - binary: observe
    id: observe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{.CommitTimestamp}}"
  - binary: observe
    id: observe-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: "{{.CommitTimestamp}}"
    hooks:
      post:
        - cmd: "{{ dir (dir (dir .Path)) }}/s/windows-sign.sh '{{ .Path }}'"
  - binary: observe
    id: observe-macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{.CommitTimestamp}}"
    hooks:
      post: codesign --sign A69028128959F0439E6330344FCAD22D6CF8F59F --prefix com.observeinc.developer. --options runtime --timestamp "{{.Path}}"
archives:
  - id: observe
    format: zip
    files:
    - README.md
    - observe_completions_bash.sh
    wrap_in_directory: true
    strip_parent_binary_folder: true
    rlcp: true
    builds:
      - observe
      - observe-windows
    format_overrides:
      - goos: linux
        format: "tar.gz"
  - id: observe-macos
    format: zip
    files:
    - README.md
    - observe_completions_bash.sh
    wrap_in_directory: true
    strip_parent_binary_folder: true
    rlcp: true
    builds:
      - observe-macos
    format_overrides:
      - goos: linux
        format: "tar.gz"
signs:
  - ids:
      - observe-macos
    signature: "${artifact}"
    cmd: sh
    args:
      - "-c"
      - "s/apple-sign.sh ${artifact}"
    artifacts: archive
    output: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
